/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.jhu.cvrg.portal.guidgenerator.model.impl;

import com.jhu.cvrg.portal.guidgenerator.model.Site;
import com.jhu.cvrg.portal.guidgenerator.model.SiteModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

/**
 * The base model implementation for the Site service. Represents a row in the &quot;JHU_Site&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.jhu.cvrg.portal.guidgenerator.model.SiteModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SiteImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a site model instance should use the {@link com.jhu.cvrg.portal.guidgenerator.model.Site} interface instead.
 * </p>
 *
 * @author Chris Jurado
 * @see SiteImpl
 * @see com.jhu.cvrg.portal.guidgenerator.model.Site
 * @see com.jhu.cvrg.portal.guidgenerator.model.SiteModel
 * @generated
 */
public class SiteModelImpl extends BaseModelImpl<Site> implements SiteModel {
	public static final String TABLE_NAME = "JHU_Site";
	public static final Object[][] TABLE_COLUMNS = {
			{ "siteId", new Integer(Types.BIGINT) },
			{ "siteAcronym", new Integer(Types.VARCHAR) },
			{ "siteName", new Integer(Types.VARCHAR) }
		};
	public static final String TABLE_SQL_CREATE = "create table JHU_Site (siteId LONG not null primary key,siteAcronym VARCHAR(75) null,siteName VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table JHU_Site";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.jhu.cvrg.portal.guidgenerator.model.Site"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.jhu.cvrg.portal.guidgenerator.model.Site"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.jhu.cvrg.portal.guidgenerator.model.Site"));

	public SiteModelImpl() {
	}

	public long getPrimaryKey() {
		return _siteId;
	}

	public void setPrimaryKey(long pk) {
		setSiteId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_siteId);
	}

	public long getSiteId() {
		return _siteId;
	}

	public void setSiteId(long siteId) {
		_siteId = siteId;
	}

	public String getSiteAcronym() {
		if (_siteAcronym == null) {
			return StringPool.BLANK;
		}
		else {
			return _siteAcronym;
		}
	}

	public void setSiteAcronym(String siteAcronym) {
		_siteAcronym = siteAcronym;
	}

	public String getSiteName() {
		if (_siteName == null) {
			return StringPool.BLANK;
		}
		else {
			return _siteName;
		}
	}

	public void setSiteName(String siteName) {
		_siteName = siteName;
	}

	public Site toEscapedModel() {
		if (isEscapedModel()) {
			return (Site)this;
		}
		else {
			return (Site)Proxy.newProxyInstance(Site.class.getClassLoader(),
				new Class[] { Site.class }, new AutoEscapeBeanHandler(this));
		}
	}

	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					Site.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	public Object clone() {
		SiteImpl siteImpl = new SiteImpl();

		siteImpl.setSiteId(getSiteId());

		siteImpl.setSiteAcronym(getSiteAcronym());

		siteImpl.setSiteName(getSiteName());

		return siteImpl;
	}

	public int compareTo(Site site) {
		long pk = site.getPrimaryKey();

		if (getPrimaryKey() < pk) {
			return -1;
		}
		else if (getPrimaryKey() > pk) {
			return 1;
		}
		else {
			return 0;
		}
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Site site = null;

		try {
			site = (Site)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long pk = site.getPrimaryKey();

		if (getPrimaryKey() == pk) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return (int)getPrimaryKey();
	}

	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{siteId=");
		sb.append(getSiteId());
		sb.append(", siteAcronym=");
		sb.append(getSiteAcronym());
		sb.append(", siteName=");
		sb.append(getSiteName());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.jhu.cvrg.portal.guidgenerator.model.Site");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>siteId</column-name><column-value><![CDATA[");
		sb.append(getSiteId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>siteAcronym</column-name><column-value><![CDATA[");
		sb.append(getSiteAcronym());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>siteName</column-name><column-value><![CDATA[");
		sb.append(getSiteName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private long _siteId;
	private String _siteAcronym;
	private String _siteName;
	private transient ExpandoBridge _expandoBridge;
}