/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.jhu.cvrg.portal.guidgenerator.model.impl;

import com.jhu.cvrg.portal.guidgenerator.model.Study;
import com.jhu.cvrg.portal.guidgenerator.model.StudyModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

/**
 * The base model implementation for the Study service. Represents a row in the &quot;JHU_Study&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.jhu.cvrg.portal.guidgenerator.model.StudyModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StudyImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a study model instance should use the {@link com.jhu.cvrg.portal.guidgenerator.model.Study} interface instead.
 * </p>
 *
 * @author Chris Jurado
 * @see StudyImpl
 * @see com.jhu.cvrg.portal.guidgenerator.model.Study
 * @see com.jhu.cvrg.portal.guidgenerator.model.StudyModel
 * @generated
 */
public class StudyModelImpl extends BaseModelImpl<Study> implements StudyModel {
	public static final String TABLE_NAME = "JHU_Study";
	public static final Object[][] TABLE_COLUMNS = {
			{ "studyId", new Integer(Types.BIGINT) },
			{ "studyAcronym", new Integer(Types.VARCHAR) },
			{ "studyName", new Integer(Types.VARCHAR) }
		};
	public static final String TABLE_SQL_CREATE = "create table JHU_Study (studyId LONG not null primary key,studyAcronym VARCHAR(75) null,studyName VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table JHU_Study";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.jhu.cvrg.portal.guidgenerator.model.Study"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.jhu.cvrg.portal.guidgenerator.model.Study"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.jhu.cvrg.portal.guidgenerator.model.Study"));

	public StudyModelImpl() {
	}

	public long getPrimaryKey() {
		return _studyId;
	}

	public void setPrimaryKey(long pk) {
		setStudyId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_studyId);
	}

	public long getStudyId() {
		return _studyId;
	}

	public void setStudyId(long studyId) {
		_studyId = studyId;
	}

	public String getStudyAcronym() {
		if (_studyAcronym == null) {
			return StringPool.BLANK;
		}
		else {
			return _studyAcronym;
		}
	}

	public void setStudyAcronym(String studyAcronym) {
		_studyAcronym = studyAcronym;
	}

	public String getStudyName() {
		if (_studyName == null) {
			return StringPool.BLANK;
		}
		else {
			return _studyName;
		}
	}

	public void setStudyName(String studyName) {
		_studyName = studyName;
	}

	public Study toEscapedModel() {
		if (isEscapedModel()) {
			return (Study)this;
		}
		else {
			return (Study)Proxy.newProxyInstance(Study.class.getClassLoader(),
				new Class[] { Study.class }, new AutoEscapeBeanHandler(this));
		}
	}

	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					Study.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	public Object clone() {
		StudyImpl studyImpl = new StudyImpl();

		studyImpl.setStudyId(getStudyId());

		studyImpl.setStudyAcronym(getStudyAcronym());

		studyImpl.setStudyName(getStudyName());

		return studyImpl;
	}

	public int compareTo(Study study) {
		long pk = study.getPrimaryKey();

		if (getPrimaryKey() < pk) {
			return -1;
		}
		else if (getPrimaryKey() > pk) {
			return 1;
		}
		else {
			return 0;
		}
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Study study = null;

		try {
			study = (Study)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long pk = study.getPrimaryKey();

		if (getPrimaryKey() == pk) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return (int)getPrimaryKey();
	}

	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{studyId=");
		sb.append(getStudyId());
		sb.append(", studyAcronym=");
		sb.append(getStudyAcronym());
		sb.append(", studyName=");
		sb.append(getStudyName());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.jhu.cvrg.portal.guidgenerator.model.Study");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>studyId</column-name><column-value><![CDATA[");
		sb.append(getStudyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>studyAcronym</column-name><column-value><![CDATA[");
		sb.append(getStudyAcronym());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>studyName</column-name><column-value><![CDATA[");
		sb.append(getStudyName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private long _studyId;
	private String _studyAcronym;
	private String _studyName;
	private transient ExpandoBridge _expandoBridge;
}