/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.jhu.cvrg.portal.guidgenerator.model.impl;

import com.jhu.cvrg.portal.guidgenerator.model.SubjectHash;
import com.jhu.cvrg.portal.guidgenerator.model.SubjectHashModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

/**
 * The base model implementation for the SubjectHash service. Represents a row in the &quot;JHU_SubjectHash&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.jhu.cvrg.portal.guidgenerator.model.SubjectHashModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SubjectHashImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a subject hash model instance should use the {@link com.jhu.cvrg.portal.guidgenerator.model.SubjectHash} interface instead.
 * </p>
 *
 * @author Chris Jurado
 * @see SubjectHashImpl
 * @see com.jhu.cvrg.portal.guidgenerator.model.SubjectHash
 * @see com.jhu.cvrg.portal.guidgenerator.model.SubjectHashModel
 * @generated
 */
public class SubjectHashModelImpl extends BaseModelImpl<SubjectHash>
	implements SubjectHashModel {
	public static final String TABLE_NAME = "JHU_SubjectHash";
	public static final Object[][] TABLE_COLUMNS = {
			{ "subjectHashId", new Integer(Types.BIGINT) },
			{ "subjectHashValue", new Integer(Types.VARCHAR) }
		};
	public static final String TABLE_SQL_CREATE = "create table JHU_SubjectHash (subjectHashId LONG not null primary key,subjectHashValue VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table JHU_SubjectHash";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.jhu.cvrg.portal.guidgenerator.model.SubjectHash"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.jhu.cvrg.portal.guidgenerator.model.SubjectHash"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.jhu.cvrg.portal.guidgenerator.model.SubjectHash"));

	public SubjectHashModelImpl() {
	}

	public long getPrimaryKey() {
		return _subjectHashId;
	}

	public void setPrimaryKey(long pk) {
		setSubjectHashId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_subjectHashId);
	}

	public long getSubjectHashId() {
		return _subjectHashId;
	}

	public void setSubjectHashId(long subjectHashId) {
		_subjectHashId = subjectHashId;
	}

	public String getSubjectHashValue() {
		if (_subjectHashValue == null) {
			return StringPool.BLANK;
		}
		else {
			return _subjectHashValue;
		}
	}

	public void setSubjectHashValue(String subjectHashValue) {
		_subjectHashValue = subjectHashValue;
	}

	public SubjectHash toEscapedModel() {
		if (isEscapedModel()) {
			return (SubjectHash)this;
		}
		else {
			return (SubjectHash)Proxy.newProxyInstance(SubjectHash.class.getClassLoader(),
				new Class[] { SubjectHash.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					SubjectHash.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	public Object clone() {
		SubjectHashImpl subjectHashImpl = new SubjectHashImpl();

		subjectHashImpl.setSubjectHashId(getSubjectHashId());

		subjectHashImpl.setSubjectHashValue(getSubjectHashValue());

		return subjectHashImpl;
	}

	public int compareTo(SubjectHash subjectHash) {
		long pk = subjectHash.getPrimaryKey();

		if (getPrimaryKey() < pk) {
			return -1;
		}
		else if (getPrimaryKey() > pk) {
			return 1;
		}
		else {
			return 0;
		}
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		SubjectHash subjectHash = null;

		try {
			subjectHash = (SubjectHash)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long pk = subjectHash.getPrimaryKey();

		if (getPrimaryKey() == pk) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return (int)getPrimaryKey();
	}

	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{subjectHashId=");
		sb.append(getSubjectHashId());
		sb.append(", subjectHashValue=");
		sb.append(getSubjectHashValue());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.jhu.cvrg.portal.guidgenerator.model.SubjectHash");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>subjectHashId</column-name><column-value><![CDATA[");
		sb.append(getSubjectHashId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>subjectHashValue</column-name><column-value><![CDATA[");
		sb.append(getSubjectHashValue());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private long _subjectHashId;
	private String _subjectHashValue;
	private transient ExpandoBridge _expandoBridge;
}