/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.jhu.cvrg.portal.guidgenerator.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the StudySite service. Represents a row in the &quot;JHU_StudySite&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.jhu.cvrg.portal.guidgenerator.model.impl.StudySiteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.jhu.cvrg.portal.guidgenerator.model.impl.StudySiteImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a study site model instance should use the {@link StudySite} interface instead.
 * </p>
 *
 * @author Chris Jurado
 * @see StudySite
 * @see com.jhu.cvrg.portal.guidgenerator.model.impl.StudySiteImpl
 * @see com.jhu.cvrg.portal.guidgenerator.model.impl.StudySiteModelImpl
 * @generated
 */
public interface StudySiteModel extends BaseModel<StudySite> {
	/**
	 * Gets the primary key of this study site.
	 *
	 * @return the primary key of this study site
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this study site
	 *
	 * @param pk the primary key of this study site
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the study site id of this study site.
	 *
	 * @return the study site id of this study site
	 */
	public long getStudySiteId();

	/**
	 * Sets the study site id of this study site.
	 *
	 * @param studySiteId the study site id of this study site
	 */
	public void setStudySiteId(long studySiteId);

	/**
	 * Gets the study id of this study site.
	 *
	 * @return the study id of this study site
	 */
	public long getStudyId();

	/**
	 * Sets the study id of this study site.
	 *
	 * @param studyId the study id of this study site
	 */
	public void setStudyId(long studyId);

	/**
	 * Gets the site id of this study site.
	 *
	 * @return the site id of this study site
	 */
	public long getSiteId();

	/**
	 * Sets the site id of this study site.
	 *
	 * @param siteId the site id of this study site
	 */
	public void setSiteId(long siteId);

	/**
	 * Gets the linking direction of this study site.
	 *
	 * @return the linking direction of this study site
	 */
	public int getLinkingDirection();

	/**
	 * Sets the linking direction of this study site.
	 *
	 * @param linkingDirection the linking direction of this study site
	 */
	public void setLinkingDirection(int linkingDirection);

	/**
	 * Gets a copy of this study site as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public StudySite toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(StudySite studySite);

	public int hashCode();

	public String toString();

	public String toXmlString();
}