/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.jhu.cvrg.portal.guidgenerator.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the SubjectHash service. Represents a row in the &quot;JHU_SubjectHash&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.jhu.cvrg.portal.guidgenerator.model.impl.SubjectHashModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.jhu.cvrg.portal.guidgenerator.model.impl.SubjectHashImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a subject hash model instance should use the {@link SubjectHash} interface instead.
 * </p>
 *
 * @author Chris Jurado
 * @see SubjectHash
 * @see com.jhu.cvrg.portal.guidgenerator.model.impl.SubjectHashImpl
 * @see com.jhu.cvrg.portal.guidgenerator.model.impl.SubjectHashModelImpl
 * @generated
 */
public interface SubjectHashModel extends BaseModel<SubjectHash> {
	/**
	 * Gets the primary key of this subject hash.
	 *
	 * @return the primary key of this subject hash
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this subject hash
	 *
	 * @param pk the primary key of this subject hash
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the subject hash id of this subject hash.
	 *
	 * @return the subject hash id of this subject hash
	 */
	public long getSubjectHashId();

	/**
	 * Sets the subject hash id of this subject hash.
	 *
	 * @param subjectHashId the subject hash id of this subject hash
	 */
	public void setSubjectHashId(long subjectHashId);

	/**
	 * Gets the subject hash value of this subject hash.
	 *
	 * @return the subject hash value of this subject hash
	 */
	@AutoEscape
	public String getSubjectHashValue();

	/**
	 * Sets the subject hash value of this subject hash.
	 *
	 * @param subjectHashValue the subject hash value of this subject hash
	 */
	public void setSubjectHashValue(String subjectHashValue);

	/**
	 * Gets a copy of this subject hash as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public SubjectHash toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SubjectHash subjectHash);

	public int hashCode();

	public String toString();

	public String toXmlString();
}